# Generated by Django 2.1.3 on 2018-11-22 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181122_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='belong_to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.User'),
        ),
    ]
